name: PremiumVanish
main: de.myzelyam.premiumvanish.bukkit.PremiumVanish
author: MyzelYam
description: Ultimate admin tool to fully vanish from the server and spy on potential rule breakers
version: 2.6.2
website: https://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/
depend: [ProtocolLib]
api-version: 1.13
softdepend:
- LibsDisguises
- DisguiseCraft
- dynmap
- Essentials
- TrailGUI
- SuperTrails
- PlaceholderAPI
- CustomParticleEffects
- Citizens
- NametagEdit
- MVdWPlaceholderAPI
- Vault
- EnjinMinecraftPlugin
- ServerListPlus
- CMI
- DiscordSRV
permissions:
  pv.*:
    children:
      pv.use: true
      pv.see: true
      pv.reload: true
      pv.logout: true
      pv.login: true
      pv.others: true
      pv.list: true
      pv.keepfly: true
      pv.toggleitems: true
      pv.recreatefiles: true
      pv.notoggle: true
      pv.unlock: true
      pv.tptg: true
      pv.bypasscmd: true
      pv.joinvanished: true
      pv.coords: true
      pv.notify: true
      pv.breakblocks: true
      pv.placeblocks: true
      pv.useblocks: true
      pv.interact: true
      pv.damage: true
      pv.dropitems: true
      pv.spectatortp: true
      pv.creativeitems: true
      pv.modifyowninv: true
      pv.modifyotherinv: true
      pv.bypassspam: true
      pv.scoreboard: true
      pv.switch: true
      pv.setlevel: true
      pv.printstacktrace: true
      pv.togglescoreboard: true
    description: Grants you all PremiumVanish permissions
  premiumvanish.*:
    children:
      pv.*: true
    description: Grants you all PremiumVanish permissions
  pv.see:
    description: You can see other vanished players
  pv.notoggle:
    description: Other players cannot hide/show you if you're online
  pv.keepfly:
    description: You can always keep flying when you reappear
  pv.joinvanished:
    description: You always join vanished (must be enabled in config)
  pv.switch:
    description: You can toggle spectator mode by pressing shift twice
  pv.openplayerinv:
    description: You can open a player's inventory by right-clicking the player
  pv.spectatoreditinv:
    description: You can edit inventories in spectator mode